# Generated by Django 5.2.12 on 2026-03-18 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_master_options_alter_masterservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('exception_type', models.CharField(choices=[('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('training', 'Обучение'), ('day_off', 'Выходной'), ('custom', 'Другое')], default='custom', max_length=30, verbose_name='Тип исключения')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Окончание')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('is_full_day', models.BooleanField(default=True, verbose_name='На весь день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='catalog.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Исключение в расписании',
                'verbose_name_plural': 'Исключения в расписании',
                'ordering': ('-date', 'master'),
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало блокировки')),
                ('end_at', models.DateTimeField(verbose_name='Окончание блокировки')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='catalog.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Блокировка времени',
                'verbose_name_plural': 'Блокировки времени',
                'ordering': ('-start_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Выходной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='catalog.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Рабочее время',
                'verbose_name_plural': 'Рабочее время',
                'ordering': ('master', 'weekday'),
                'constraints': [models.UniqueConstraint(fields=('master', 'weekday'), name='unique_master_weekday_working_hours')],
            },
        ),
    ]
