# Generated by Django 5.2.12 on 2026-03-18 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_master_options_alter_masterservice_options_and_more'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало записи')),
                ('end_at', models.DateTimeField(verbose_name='Окончание записи')),
                ('status', models.CharField(choices=[('pending', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('no_show', 'Не пришёл')], default='pending', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('website', 'Сайт'), ('admin', 'Администратор'), ('phone', 'Телефон'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('other', 'Другое')], default='website', max_length=20, verbose_name='Источник')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Можно оставить пустым, если цена еще не зафиксирована.', max_digits=10, null=True, verbose_name='Цена на момент записи')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждена')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменена')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client', verbose_name='Клиент')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='catalog.master', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='catalog.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('-start_at',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appointments/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='booking.appointment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Файл записи',
                'verbose_name_plural': 'Файлы записей',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('no_show', 'Не пришёл')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('pending', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('no_show', 'Не пришёл')], max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='booking.appointment', verbose_name='Запись')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'История статуса записи',
                'verbose_name_plural': 'История статусов записей',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['master', 'start_at'], name='appointment_master_start_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_at'], name='appointment_status_start_idx'),
        ),
    ]
