# Generated by Django 5.2.12 on 2026-03-18 10:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'service category',
                'verbose_name_plural': 'service categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='display name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='photo')),
                ('short_bio', models.CharField(blank=True, max_length=500, verbose_name='short bio')),
                ('full_bio', models.TextField(blank=True, verbose_name='full bio')),
                ('experience_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='experience in years')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'master',
                'verbose_name_plural': 'masters',
                'ordering': ('sort_order', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='catalog.master', verbose_name='master')),
            ],
            options={
                'verbose_name': 'portfolio item',
                'verbose_name_plural': 'portfolio items',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='short description')),
                ('full_description', models.TextField(blank=True, verbose_name='full description')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the service in minutes.', validators=[django.core.validators.MinValueValidator(15)], verbose_name='duration in minutes')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base price')),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='buffer before in minutes')),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='buffer after in minutes')),
                ('prepayment_required', models.BooleanField(default=False, verbose_name='prepayment required')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use service base price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='custom price')),
                ('custom_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Leave empty to use service default duration.', null=True, validators=[django.core.validators.MinValueValidator(15)], verbose_name='custom duration in minutes')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='catalog.master', verbose_name='master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='catalog.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'master service',
                'verbose_name_plural': 'master services',
                'ordering': ('master', 'service'),
                'constraints': [models.UniqueConstraint(fields=('master', 'service'), name='unique_master_service')],
            },
        ),
    ]
