# Generated by Django 5.2.12 on 2026-03-18 11:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('sort_order', 'display_name'), 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='masterservice',
            options={'ordering': ('master', 'service'), 'verbose_name': 'Услуга мастера', 'verbose_name_plural': 'Услуги мастеров'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ('sort_order', 'title'), 'verbose_name': 'Элемент портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Категория услуги', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='master',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='Имя для сайта'),
        ),
        migrations.AlterField(
            model_name='master',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Опыт (лет)'),
        ),
        migrations.AlterField(
            model_name='master',
            name='full_bio',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='master',
            name='short_bio',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='master',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='master',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='master',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='custom_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, чтобы использовать стандартную длительность услуги.', null=True, validators=[django.core.validators.MinValueValidator(15)], verbose_name='Индивидуальная длительность (мин.)'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Оставьте пустым, чтобы использовать базовую цену услуги.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Индивидуальная цена'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='catalog.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='catalog.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='portfolio/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='catalog.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='buffer_after_minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Буфер после услуги (мин.)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='buffer_before_minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Буфер до услуги (мин.)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Длительность услуги в минутах.', validators=[django.core.validators.MinValueValidator(15)], verbose_name='Длительность (мин.)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='prepayment_required',
            field=models.BooleanField(default=False, verbose_name='Нужна предоплата'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
    ]
