# Generated by Django 5.2.12 on 2026-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_master_options_alter_masterservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото услуги'),
        ),
    ]
