# Generated by Django 5.2.12 on 2026-06-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Если указан, мастер будет получать уведомления о своих новых записях.', max_length=64, verbose_name='Telegram chat ID'),
        ),
    ]
