# Generated by Django 5.2.12 on 2026-06-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='weekday_hours',
            field=models.CharField(blank=True, default='10:00 — 21:00', max_length=50, verbose_name='Время работы в будни'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekday_hours_label',
            field=models.CharField(blank=True, default='Пн-Пт', max_length=50, verbose_name='Подпись будних дней'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekend_hours',
            field=models.CharField(blank=True, default='11:00 — 19:00', max_length=50, verbose_name='Время работы в выходные'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekend_hours_label',
            field=models.CharField(blank=True, default='Сб-Вс', max_length=50, verbose_name='Подпись выходных дней'),
        ),
    ]
